import type { Recipe } from "../types/recipe";

export const fakeRecipes: Recipe[] = [
  {
    title: "Chicken Potato Surprise",
    ingredients: [
      "1 lb. boneless, skinless chicken breast, cut into bite-sized pieces",
      "1/2 lb. red potatoes",
      "diced 1/2 onion",
      "diced 1/2 green pepper",
      "diced 1 clove garlic",
      "minced 1 tsp. olive oil",
      "1/2 tsp salt",
      "1/4 tsp. black pepper",
    ],
    directions: [
      "Preheat oven to 375 degrees F (190 degrees C)",
      "In a large bowl, combine chicken, potatoes, onion, green pepper, garlic, olive oil, salt, and black pepper",
      "Transfer the mixture to a 9x13 inch baking dish",
      "Bake for 30-40 minutes, or until chicken is cooked through and potatoes are tender",
      "Serve with a side salad or steamed vegetables,",
    ],
  },
  {
    title: "Lasagna",
    ingredients: [
      "1 lb. boneless, skinless chicken breast, cut into bite-sized pieces",
      "1/2 lb. red potatoes",
      "diced 1/2 onion",
      "diced 1/2 green pepper",
      "diced 1 clove garlic",
      "minced 1 tsp. olive oil",
      "1/2 tsp salt",
      "1/4 tsp. black pepper",
    ],
    directions: [
      "Preheat oven to 375 degrees F (190 degrees C)",
      "In a large bowl, combine chicken, potatoes, onion, green pepper, garlic, olive oil, salt, and black pepper",
      "Transfer the mixture to a 9x13 inch baking dish",
      "Bake for 30-40 minutes, or until chicken is cooked through and potatoes are tender",
      "Serve with a side salad or steamed vegetables,",
    ],
  },
  {
    title: "Pizza",
    ingredients: [
      "1 lb. boneless, skinless chicken breast, cut into bite-sized pieces",
      "1/2 lb. red potatoes",
      "diced 1/2 onion",
      "diced 1/2 green pepper",
      "diced 1 clove garlic",
      "minced 1 tsp. olive oil",
      "1/2 tsp salt",
      "1/4 tsp. black pepper",
    ],
    directions: [
      "Preheat oven to 375 degrees F (190 degrees C)",
      "In a large bowl, combine chicken, potatoes, onion, green pepper, garlic, olive oil, salt, and black pepper",
      "Transfer the mixture to a 9x13 inch baking dish",
      "Bake for 30-40 minutes, or until chicken is cooked through and potatoes are tender",
      "Serve with a side salad or steamed vegetables,",
    ],
  },
  {
    title: "Pasta",
    ingredients: [
      "1 lb. boneless, skinless chicken breast, cut into bite-sized pieces",
      "1/2 lb. red potatoes",
      "diced 1/2 onion",
      "diced 1/2 green pepper",
      "diced 1 clove garlic",
      "minced 1 tsp. olive oil",
      "1/2 tsp salt",
      "1/4 tsp. black pepper",
    ],
    directions: [
      "Preheat oven to 375 degrees F (190 degrees C)",
      "In a large bowl, combine chicken, potatoes, onion, green pepper, garlic, olive oil, salt, and black pepper",
      "Transfer the mixture to a 9x13 inch baking dish",
      "Bake for 30-40 minutes, or until chicken is cooked through and potatoes are tender",
      "Serve with a side salad or steamed vegetables,",
    ],
  },
  {
    title: "Soup",
    ingredients: [
      "1 lb. boneless, skinless chicken breast, cut into bite-sized pieces",
      "1/2 lb. red potatoes",
      "diced 1/2 onion",
      "diced 1/2 green pepper",
      "diced 1 clove garlic",
      "minced 1 tsp. olive oil",
      "1/2 tsp salt",
      "1/4 tsp. black pepper",
    ],
    directions: [
      "Preheat oven to 375 degrees F (190 degrees C)",
      "In a large bowl, combine chicken, potatoes, onion, green pepper, garlic, olive oil, salt, and black pepper",
      "Transfer the mixture to a 9x13 inch baking dish",
      "Bake for 30-40 minutes, or until chicken is cooked through and potatoes are tender",
      "Serve with a side salad or steamed vegetables,",
    ],
  },
];
